### ISSUE TITLE
letters "use ? or - for blanks"

### ISSUE THREAD

**Issue by xz013** [DHancock/Countdown#73]
hello , thank you for smart code you are really amazing  👍 

we send charArry to  WordDictionary.Solve(charArry  as example " world ") I', asking you sir what is we have this word " worl? " last char is missing how to pass it to Solve method we can use "?" or how to do it ! 
thank you for your code and helping

**Comment by DHancock** [comment]
I think you mean using the ? character as a wild card search. This isn't possible at the moment because neither the data format used by the word dictionary or the solving code itself have been written to make that possible. It has been created simply to solve the countdown puzzle, not to be a general purpose anagram solver. Anagram solving algorithms can be found using google, for example:

https://hackernoon.com/an-algorithm-for-finding-anagrams-2fe7655de85b
